{
 "title": "Dashboard Pong",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jobs",
    "query": {
     "query": "label_values(container_label_com_docker_compose_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up) or vector(0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DOWN",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up) - count(container_start_time_seconds{name!=\"\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_start_time_seconds{name!=\"\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 13, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "(rate(container_cpu_user_seconds_total{image!=\"\", name=~\"$jobs\"}[5m]) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}