# =========================
# Dockerfile pour dev
# =========================
FROM node:20

RUN apt-get update && apt-get install -y curl jq && rm -rf /var/lib/apt/lists/*

WORKDIR /app/back_to_back

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install --include=dev

COPY prisma/ ./prisma

RUN ls /app/back_to_back/prisma/schema.prisma

RUN npx prisma generate --schema /app/back_to_back/prisma/schema.prisma

COPY src ./src

EXPOSE 3042

CMD ["npm", "run", "docker:start"]
